# Generated by Django 5.1.3 on 2024-11-12 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crime_type', models.CharField(max_length=100)),
                ('sentence_type', models.CharField(choices=[('tradicional', 'Sentencia tradicional'), ('cognify', 'Rehabilitaciion por Cognify')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empathy_level', models.IntegerField(default=1)),
                ('regret_level', models.IntegerField(default=1)),
                ('memory_description', models.TextField()),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.criminal')),
            ],
        ),
    ]
